from enum import Enum

class EnvKeys(Enum):
    APP_HOST='APP_HOST'
    APP_PORT='APP_PORT'
    APP_ENVIROMENT='APP_ENVIROMENT'
    # Logging settings
    LOG_LEVEL='LOG_LEVEL'
    LOG_FILE='LOG_FILE'
    APP_LOG_FILE='APP_LOG_FILE'
    APP_LOGGING_LEVEL='APP_LOGGING_LEVEL'
    APP_LOGGING_HANDLER_NAME='APP_LOGGING_HANDLER_NAME'
    APP_LOGGING_FOLDER='APP_LOGGING_FOLDER'
    APP_LOGGING_FORMATTER='APP_LOGGING_FORMATTER'
    APP_LOGGING_DATEFORMAT='APP_LOGGING_DATEFORMATTER'
    APP_LOGGING_MAXBYTES='APP_LOGGING_MAXBYTES'
    APP_LOGGING_BACKUPCOUNT='APP_LOGGING_BACKUPCOUNT'
    # IDENITY
    APP_USER_AGENT='APP_USER_AGENT'
    SQLITE_DB_PATH='SQLITE_DB_PATH'
    # Folders
    UPLOAD_DIR='UPLOAD_DIR'
    UPLOAD_ALLOWED_EXTENTIONS='APLOAD_ALLOWED_EXTENTIONS'
    # OPENAI
    OPENAI_KEY='OPENAI_KEY'
    OPENAI_MODEL='OPENAI_MODEL'
    OPENAI_VERBOSE='OPENAI_VERBOSE'
    OPENAI_TEMPERATURE='OPENAI_TEMPERATURE'
    # Postgres
    POSTGRES_DB_HOST='POSTGRES_DB_HOST'
    POSTGRES_DB_NAME='POSTGRES_DB_NAME'
    POSTGRES_DB_USER='POSTGRES_DB_USER'
    POSTGRES_DB_PASSWORD='POSTGRES_DB_PASSWORD'
    POSTGRES_DB_PORT='POSTGRES_DB_PORT'
    POSTGRES_DB_SCHEMA='POSTGRES_DB_SCHEMA'
    POSTGRES_SSLMODE="POSTGRES_SSLMODE"
     